### PR TITLE
Update to COS TDS format

### PR DESCRIPTION
**Pull request by sean-lockwood**
Now supports `APERTURE`='ANY' and the new `CENWAVE` column.

Valid for all TDS files in CRDS (https://hst-crds.stsci.edu) active as of 2020 Feb 05.  Given the added cenwave column, old data files will fail until their TDSTAB entry is updated to point at the new files.  To do this, users may either re-download their data, manually update TDSTAB, or run the CRDS command line tool:  https://hst-crds.stsci.edu/docs/cmdline_bestrefs

I have chosen not to provide backwards compatibility with the old format TDSTABs (without `CENWAVE`), though Justin may disagree.

### CODE REVIEW

**Comment by justincely** [comment]
@sean-lockwood thanks for the PR.  Not sure if CI is still hooked up on this, if it doesn't start I'll take a look.

Re: the backwards incompatibility, is there an indicator in the TDSTAB that we could use to trigger different lookup logic around cenwave?

**Comment by sean-lockwood** [comment]
@justincely 
Perhaps for the new version: `if 'CENWAVE' in tds_data.columns.names:`

I would add a warning message for the old-format file, as it will likely be outdated.

**Comment by justincely** [comment]
Yeah that can work.  Not perfect, but good enough for these simple purposes. 

Ya'll should add some SEMVER header to the reffiles.  Could be really nice for tracking when backwards incompatible changes are made and how to trigger behavior and warnings like this.  Just a thought.

**Comment by jcv109** [comment]
Dear Gentlemen,
Thanks for the very quick response. Just for completess, as far as I see, the proposed change in cos.py will accept reading new tds file. However, as several records will be now returned, the following error condition in the source code (that detects if more than one entry) will still be activated. May be the code should take a decision on how to handle to have potentially different entries? Or to select arbitrarily the central wavelenght of the different records? 
Or may be I am fully misunderstanding the issue? Thanks in any case for taking care of all this stuff, because your package is certainly very appreciated.

**Comment by sean-lockwood** [comment]
@jcv109 
After this change, the code should still select only one matching record from the new TDSTABs.  While the COS Team changed the format of the reference file to include a new selection column (`CENWAVE`), this is still a configurable observing mode (grating tilt) unique to each observation (and not a more general wavelength array).  I included it in the new matching logic.

The new file also combines PSA & BOA into one entry (`ANY`), so multiple rows will not be returned on this criteria.

**Comment by justincely** [comment]
well, ci is totally borked - i can't even get it to show up in travis; likely because they moved orgs or my integration is so very out of date.  That'll need to be fixed before this goes in; i'll try to hook up github actions or re-enable travis this weekend.

@jcv109 if you want to test and use this in the meantime, you can clone the repo, checkout this branch specifically, and install into your local python environment.

**Comment by jcv109** [comment]
Dear gentlemen,
Just for speeding up, I pasted the new lines into the previously cloned code and processed a single file. It worked nicely. I will run everything more carefully now, but at glance it seems to be fully solved. Congratulations again for your package and thank you very much for the very quick support and explanations about the new condition!

**Comment by justincely** [comment]
cool, travis finally saw this and ran.  I'll fix the github actions that I tried to add later, but this is good to merge.

**Comment by justincely** [comment]
@sean-lockwood since yours is in a fork, i'll merge and do a fix for the backwards compat before a release.

**Pull request merged**
